### ISSUE TITLE
Clean git-clone gives build error

### ISSUE THREAD

**Issue by arthurvb** [dstl/baleen#87]
Just did a clone of the repo after installing the latest JDK and Maven on OSX.
After using the command `mvn package -Dmaven.test.skip=true` it fails with the following message: 

``` 
Failed to execute goal on project baleen-resources: Could not resolve dependencies for project uk.gov.dstl.baleen:baleen-resources:jar:2.6.1-SNAPSHOT: Could not find artifact uk.gov.dstl.baleen:baleen-uima:jar:tests:2.6.1-SNAPSHOT 
```

Also without the test option, it won't compile. Hopefully you can tell me what went wrong.

Best regards

**Comment by JohnDaws** [comment]
Thanks for feeding this back. There is a chance I have broken something when upgrading to version 2.6.1-SNAPSHOT.

Hopefully you will be able to get started with the pre-compiled Baleen available here: https://github.com/dstl/baleen/releases

Alternatively if you checkout the code as per commit `67976e105eb34d9decaa03a091896cc7c8ef3c51` then you will have the code for v2.6.0 which should build.

In the mean time I will leave this open in case I have accidentally broken something...

**Comment by JohnDaws** [comment]
Please try building with `mvn package -DskipTests` rather than using the `-Dmaven.test.skip=true` flag.

According to [this answer](https://stackoverflow.com/questions/25639336/whats-the-difference-between-dskiptests-and-dmaven-test-skip-true), `-Dmaven.test.skip=true` will not compile or run the tests whereas `-DskipTests` will compile but not run the tests. 

The error message that you are seeing (which I have replicated) sounds like it requires a test from `baleen-uima` to have been compiled in order to resolve the dependencies for `baleen-resources`.

For me `mvn package -DskipTests` fixed that. Let me know if that works for you and I will close this issue.

**Comment by arthurvb** [comment]
Thank you for the answer. `mvn package -Dskiptests` seemed to work better however it stopped  with `Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project baleen-annotators`.

```[ERROR] Failures: 
[ERROR]   YYYYMMDDAssignerTest.test:29 expected:<1485147600000> but was:<1485129600000>
[INFO] 
[ERROR] Tests run: 642, Failures: 1, Errors: 0, Skipped: 1
```

I'll try the binary version as well..

**Comment by JohnDaws** [comment]
No problem. You still shouldn't be seeing that issue...

The simple fix is that you have the case incorrect on `-DskipTests`. It is case sensitive. `mvn package -DskipTests` should not run any tests and therefore should not fail any.

That said, it appears that there is a test failure on your system, so I'll leave this open and try to get to the bottom of it.

**Comment by jbaker-nca** [comment]
It's also possible if you're using the latest JDK that it's a version issue. Java/JDK 8 is currently the latest supported (see https://github.com/dstl/baleen/issues/79)

**Comment by jbaker-dstl** [comment]
@arthurvb - Could you please confirm whether this is resolved by the latest snapshot release, which adds support for newer JDKs and may fix the problem?

**Comment by jbaker-dstl** [comment]
Assuming this is resolved by the latest SNAPSHOT and the upcoming 2.7.0 release. Please reopen if this doesn't resolve your problem.
